export enum Routes {
	Login = '/login',
	Otp = '/otp',
	Home = '/home',
	AddProduct = '/products/add',
	EditProduct = '/products/edit',
	ProductList = '/products/list',
	AddBanner = '/banner/add',
	EditBanner = '/banner/edit',
	BannerList = '/banner/list',
	EditBannerImages = '/banner/edit/images',
	AddStoreProduct = '/store/products/add',
	EditStoreProduct = '/store/products/edit',
	StoresList = '/store/list',
	StoreProductList = '/store/products/list',
	StoreDetails = '/store/details',
}
